# Generated by Django 5.2.4 on 2025-08-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buslocation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Bus Location', 'verbose_name_plural': 'Bus Locations'},
        ),
        migrations.AddField(
            model_name='buslocation',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='bearing',
            field=models.FloatField(blank=True, help_text='Direction of travel in degrees', null=True),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='bus_id',
            field=models.CharField(default='bus_001', help_text='Unique bus identifier', max_length=50),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='speed',
            field=models.FloatField(blank=True, help_text='Speed in km/h', null=True),
        ),
    ]
